FROM existenz/webstack:8.2

# Install required packages and dependencies
RUN apk update
RUN apk add --no-cache \
    php82-openssl \
    php82-session \
    php82 \
    php82-posix \
    php82-tokenizer \
    php82-pdo \
    php82-pdo_mysql \
    php82-zip \
    php82-xml \
    php82-simplexml \
    php82-fileinfo \
    php82-xmlreader \
    php82-xmlwriter \
    php82-iconv \
    php82-mbstring \
    php82-curl \
    libstdc++ \
    libpq \
    php82-pecl-swoole \
    php82-pcntl \
    php82-phar \
    php82-bcmath \
    supervisor \
    php82-sodium \
    git \
    curl \
    php82-gd

# Add Composer
RUN curl -sS https://getcomposer.org/installer | php82 -- --install-dir=/usr/local/bin --filename=composer

# Set working dir
WORKDIR /var/www/html

# Copy app code
COPY . .

RUN rm -rf vendor .git

# Install PHP deps
RUN php82 /usr/local/bin/composer install

# Permissions (optional, useful for Laravel)
RUN chmod -R 755 /var/www/html

# Create php symlink for easier command access
RUN ln -s /usr/bin/php82 /usr/bin/php

# Expose the artisan ports
EXPOSE 8000
EXPOSE 8443

RUN php artisan config:clear || true
RUN php artisan optimize || true

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]